name: Optimize Images

on:
  push:
    paths:
      - "images/projects/**/*.png"
      - "images/projects/**/*.jpg"
      - "images/projects/**/*.jpeg"
  workflow_dispatch:

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y webp

      - name: Create WebP versions
        run: |
          # Process only images in the projects directory, excluding already optimized files
          find images/projects -type f \( -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" \) -not -name "*.optimized.webp" | while read file; do
            # Get the directory and filename
            dir=$(dirname "$file")
            filename=$(basename "$file")
            name="${filename%.*}"
            
            # Convert to high-quality WebP next to original file
            cwebp -q 75 -m 6 -af "$file" -o "$dir/$name.optimized.webp"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Add WebP versions of images [skip ci]"
          git push
