name: Optimize Images

on:
  push:
    paths:
      - "**.png"
      - "**.jpg"
      - "**.jpeg"
  workflow_dispatch:

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y webp

      - name: Create WebP versions
        run: |
          # Create optimized directory if it doesn't exist
          mkdir -p images/optimized

          # Function to create WebP while preserving directory structure
          process_image() {
            local file="$1"
            local dir=$(dirname "$file")
            local filename=$(basename "$file")
            local name="${filename%.*}"
            
            # Create corresponding directory in optimized
            mkdir -p "images/optimized/$dir"
            
            # Convert to high-quality WebP
            cwebp -q 90 "$file" -o "images/optimized/$dir/$name.webp"
          }

          # Process all images except those in optimized directory
          find images -type f \( -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" \) -not -path "*/optimized/*" -exec bash -c 'process_image "$0"' {} \;

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Add WebP versions of images [skip ci]"
          git push
